# config/packages/validator.yaml

framework:
    validation:
        email_validation_mode: html5
        # Enables validator auto-mapping support.
        auto_mapping:
            App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
