App\Entity\Measurement:
  properties:
    date:
      - NotBlank:
          groups: [ 'create', 'edit' ]
      - Type:
          type: \DateTime
          groups: [ 'create', 'edit' ]
    celsius:
      - NotBlank:
          groups: [ 'create', 'edit' ]
      - Type:
          type: numeric
          groups: [ 'create', 'edit' ]
      - Range:
          min: -100
          max: 100
          groups: [ 'create', 'edit' ]